[toolchain]
channel = "stable"
components = ["rustfmt", "clippy"]
targets = [
    "aarch64-linux-android",
    "armv7-linux-androideabi",
    "x86_64-linux-android",
    "i686-linux-android",
    "x86_64-pc-windows-msvc",
]
