[package]
name = "connected-desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.6", features = ["desktop"] }
dioxus-logger = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
async-std = "1.12"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
connected-core = { path = "../core" }
dirs = "5"
rfd = "0.15"
arboard = "3.6.1"
once_cell.workspace = true
mime_guess.workspace = true
base64 = "0.21"
mpris = "2.0.1"
dbus = "0.9.10"
image = "0.24"
btleplug = "0.11.8"
uuid = { workspace = true }
notify-rust = "4.10.0"

[target.'cfg(target_os = "linux")'.dependencies]
mpris-server = "0.9.0"

[features]
default = ["proximity-ble"]
proximity-ble = []
